---
- name: Setup and Deploy Application
  hosts: web_servers
  become: yes

  tasks:
    # Update the package list
    - name: Update apt package list
      apt:
        update_cache: yes

    # Install prerequisites
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker GPG key and repository
    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        state: present

    # Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # Add user to the Docker group
    - name: Add current user to the Docker group
      user:
        name: "{{ ansible_user }}"  # Dynamically adds the user from inventory
        groups: docker
        append: yes

    # Restart Docker service to apply group changes
    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    # Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Create the application directory
    - name: Create application directory only if it doesn't exist
      file:
        path: ~/frappe-docker  # Uses the home directory of the inventory user
        state: directory
        mode: '0755'

    # Copy application files from Jenkins workspace
    - name: Copy docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: ~/frappe-docker/docker-compose.yml
        mode: '0644'

    - name: Copy nginx configuration
      copy:
        src: ./nginx.conf
        dest: ~/frappe-docker/nginx.conf
        mode: '0644'

# Check if the cert-data directory exists
    - name: Check if cert-data directory exists
      stat:
        path: ~/frappe-docker/cert-data
      register: cert_data_dir

# Create cert-data directory if it does not exist
    - name: Create cert-data directory
      file:
        path: ~/frappe-docker/cert-data
        state: directory
        mode: '0755'
      when: not cert_data_dir.stat.exists

# Check if the SSL certificate file exists
    - name: Check if SSL certificate exists
      stat:
        path: ~/frappe-docker/cert-data/localhost.crt
      register: ssl_cert

# Generate self-signed SSL certificate if it does not exist
    - name: Generate self-signed SSL certificate
      command: >
        openssl req -x509 -newkey rsa:2048 -nodes
        -keyout ~/app/cert-data/localhost.key
        -out ~/app/cert-data/localhost.crt
        -days 365
        -subj "/CN=localhost"
      when: not ssl_cert.stat.exists

    # Run Docker Compose to start the application
    - name: Deploy application using Docker Compose
      command: docker-compose up -d
      args:
        chdir: ~/frappe-docker
